AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
    Function:
        Timeout: 300
        MemorySize: 128
        Runtime: nodejs18.x

Parameters:
    TursoAuthToken:
        Type: String
        Default:
    TursoDatabaseUrl:
        Type: String
        Default:
    PublicIsStagingEnv:
        Type: String
        Default:
    TsgBlogPageId:
        Type: String
        Default:
    TsgEventPageId:
        Type: String
        Default:
    TsgDatabasePageId:
        Type: String
        Default:
    NotionIntegrationSecret:
        Type: String
        Default:
        NoEcho: true

Resources:
    UpdateArticlesInCache:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/lambda/
            Handler: updateArticlesInCache.handler
            FunctionUrlConfig:
                AuthType: NONE
                Cors:
                    AllowOrigins: ["*"]
                    AllowMethods: ["GET", "POST"]
            Environment:
                Variables:
                    TURSO_AUTH_TOKEN: !Ref TursoAuthToken
                    TURSO_DATABASE_URL: !Ref TursoDatabaseUrl
                    PUBLIC_IS_STAGING_ENV: !Ref PublicIsStagingEnv
                    TSG_BLOG_PAGE_ID: !Ref TsgBlogPageId
                    TSG_EVENT_PAGE_ID: !Ref TsgEventPageId
                    TSG_DATABASE_PAGE_ID: !Ref TsgDatabasePageId
                    NOTION_INTEGRATION_SECRET: !Ref NotionIntegrationSecret
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                EntryPoints:
                    - articleHandler.ts

    GetArticlesInCache:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/lambda/
            Handler: getArticlesInCache.handler
            FunctionUrlConfig:
                AuthType: NONE
                Cors:
                    AllowOrigins: ["*"]
                    AllowMethods: ["GET", "POST"]
            Environment:
                Variables:
                    TURSO_AUTH_TOKEN: !Ref TursoAuthToken
                    TURSO_DATABASE_URL: !Ref TursoDatabaseUrl
                    PUBLIC_IS_STAGING_ENV: !Ref PublicIsStagingEnv
                    TSG_BLOG_PAGE_ID: !Ref TsgBlogPageId
                    TSG_EVENT_PAGE_ID: !Ref TsgEventPageId
                    TSG_DATABASE_PAGE_ID: !Ref TsgDatabasePageId
                    NOTION_INTEGRATION_SECRET: !Ref NotionIntegrationSecret
                    UPDATE_ARTICLES_FUNCTION_NAME: !Ref UpdateArticlesInCache
            Policies:
                - LambdaInvokeFunction:
                      FunctionName: !Ref UpdateArticlesInCache
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                EntryPoints:
                    - getArticlesInCache.ts

Outputs:
    UpdateArticlesInCacheFunctionUrl:
        Description: "Function URL for UpdateArticlesInCache"
        Value: !GetAtt UpdateArticlesInCacheFunctionUrl.FunctionUrl
    GetArticlesInCacheFunctionUrl:
        Description: "Function URL for GetArticlesInCache"
        Value: !GetAtt GetArticlesInCacheFunctionUrl.FunctionUrl
