AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
    Function:
        Timeout: 300
        MemorySize: 128
        Runtime: nodejs18.x
        Layers:
            - !Ref LibsqlLayer

Parameters:
    TursoAuthToken:
        Type: String
        Default:
    TursoDatabaseUrl:
        Type: String
        Default:
    PublicIsStagingEnv:
        Type: String
        Default:
    TsgBlogPageId:
        Type: String
        Default:
    TsgEventPageId:
        Type: String
        Default:
    TsgDatabasePageId:
        Type: String
        Default:
    NotionIntegrationSecret:
        Type: String
        Default:
        NoEcho: true
    SyncTriggerAuthToken:
        Type: String
        Default:
        NoEcho: true

Resources:
    LibsqlLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: !Sub "${AWS::StackName}-libsql-layer"
            Description: "libsql Linux x64 GNU library for Lambda"
            ContentUri: layers/libsql/libsql_layer.zip
            CompatibleRuntimes:
                - nodejs18.x
                - nodejs20.x
            CompatibleArchitectures:
                - x86_64

    ArticleUpdateQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: !Sub "${AWS::StackName}-article-update-queue"
            VisibilityTimeout: 960
            MessageRetentionPeriod: 1209600
            RedrivePolicy:
                deadLetterTargetArn: !GetAtt ArticleUpdateDLQ.Arn
                maxReceiveCount: 3

    ArticleUpdateDLQ:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: !Sub "${AWS::StackName}-article-update-dlq"
            MessageRetentionPeriod: 1209600

    SyncTrigger:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/lambda/
            Handler: syncTrigger.handler
            Layers:
                - !Ref LibsqlLayer
            FunctionUrlConfig:
                AuthType: NONE
                Cors:
                    AllowOrigins: ["*"]
                    AllowMethods: ["POST"]
            Environment:
                Variables:
                    TURSO_AUTH_TOKEN: !Ref TursoAuthToken
                    TURSO_DATABASE_URL: !Ref TursoDatabaseUrl
                    PUBLIC_IS_STAGING_ENV: !Ref PublicIsStagingEnv
                    TSG_BLOG_PAGE_ID: !Ref TsgBlogPageId
                    TSG_EVENT_PAGE_ID: !Ref TsgEventPageId
                    TSG_DATABASE_PAGE_ID: !Ref TsgDatabasePageId
                    NOTION_INTEGRATION_SECRET: !Ref NotionIntegrationSecret
                    SYNC_TRIGGER_AUTH_TOKEN: !Ref SyncTriggerAuthToken
                    QUEUE_URL: !Ref ArticleUpdateQueue
            Policies:
                - SQSSendMessagePolicy:
                      QueueName: !GetAtt ArticleUpdateQueue.QueueName
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                EntryPoints:
                    - syncTrigger.ts

    QueueProcessor:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/lambda/
            Handler: queueProcessor.handler
            Layers:
                - !Ref LibsqlLayer
            Environment:
                Variables:
                    TURSO_AUTH_TOKEN: !Ref TursoAuthToken
                    TURSO_DATABASE_URL: !Ref TursoDatabaseUrl
                    PUBLIC_IS_STAGING_ENV: !Ref PublicIsStagingEnv
                    TSG_BLOG_PAGE_ID: !Ref TsgBlogPageId
                    TSG_EVENT_PAGE_ID: !Ref TsgEventPageId
                    TSG_DATABASE_PAGE_ID: !Ref TsgDatabasePageId
                    NOTION_INTEGRATION_SECRET: !Ref NotionIntegrationSecret
                    UPDATE_ARTICLES_FUNCTION_NAME: !Ref UpdateArticlesInCache
            Events:
                SQSEvent:
                    Type: SQS
                    Properties:
                        Queue: !GetAtt ArticleUpdateQueue.Arn
                        BatchSize: 1
                        FunctionResponseTypes:
                            - ReportBatchItemFailures
            Policies:
                - Version: "2012-10-17"
                  Statement:
                      - Effect: Allow
                        Action:
                            - lambda:InvokeFunction
                        Resource: !GetAtt UpdateArticlesInCache.Arn
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                EntryPoints:
                    - queueProcessor.ts

    UpdateArticlesInCache:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/lambda/
            Handler: updateArticlesInCache.handler
            Layers:
                - !Ref LibsqlLayer
            FunctionUrlConfig:
                AuthType: NONE
                Cors:
                    AllowOrigins: ["*"]
                    AllowMethods: ["GET", "POST"]
            Environment:
                Variables:
                    TURSO_AUTH_TOKEN: !Ref TursoAuthToken
                    TURSO_DATABASE_URL: !Ref TursoDatabaseUrl
                    PUBLIC_IS_STAGING_ENV: !Ref PublicIsStagingEnv
                    TSG_BLOG_PAGE_ID: !Ref TsgBlogPageId
                    TSG_EVENT_PAGE_ID: !Ref TsgEventPageId
                    TSG_DATABASE_PAGE_ID: !Ref TsgDatabasePageId
                    NOTION_INTEGRATION_SECRET: !Ref NotionIntegrationSecret
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                EntryPoints:
                    - updateArticlesInCache.ts

    GetArticlesInCache:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/lambda/
            Handler: getArticlesInCache.handler
            Layers:
                - !Ref LibsqlLayer
            FunctionUrlConfig:
                AuthType: NONE
                Cors:
                    AllowOrigins: ["*"]
                    AllowMethods: ["GET", "POST"]
            Environment:
                Variables:
                    TURSO_AUTH_TOKEN: !Ref TursoAuthToken
                    TURSO_DATABASE_URL: !Ref TursoDatabaseUrl
                    PUBLIC_IS_STAGING_ENV: !Ref PublicIsStagingEnv
                    TSG_BLOG_PAGE_ID: !Ref TsgBlogPageId
                    TSG_EVENT_PAGE_ID: !Ref TsgEventPageId
                    TSG_DATABASE_PAGE_ID: !Ref TsgDatabasePageId
                    NOTION_INTEGRATION_SECRET: !Ref NotionIntegrationSecret
                    UPDATE_ARTICLES_FUNCTION_NAME: !Ref UpdateArticlesInCache
            Policies:
                - Version: "2012-10-17"
                  Statement:
                      - Effect: Allow
                        Action:
                            - lambda:InvokeFunction
                        Resource: !GetAtt UpdateArticlesInCache.Arn
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                EntryPoints:
                    - getArticlesInCache.ts

Outputs:
    UpdateArticlesInCacheFunctionUrl:
        Description: "Function URL for UpdateArticlesInCache"
        Value: !GetAtt UpdateArticlesInCacheFunctionUrl.FunctionUrl
    GetArticlesInCacheFunctionUrl:
        Description: "Function URL for GetArticlesInCache"
        Value: !GetAtt GetArticlesInCacheFunctionUrl.FunctionUrl
    SyncTriggerFunctionUrl:
        Description: "Function URL for SyncTrigger"
        Value: !GetAtt SyncTriggerFunctionUrl.FunctionUrl
    ArticleUpdateQueueUrl:
        Description: "URL for the Article Update Queue"
        Value: !Ref ArticleUpdateQueue
    ArticleUpdateDLQUrl:
        Description: "URL for the Article Update Dead Letter Queue"
        Value: !Ref ArticleUpdateDLQ
    LibsqlLayerArn:
        Description: "ARN of the libsql Lambda Layer"
        Value: !Ref LibsqlLayer
        Export:
            Name: !Sub "${AWS::StackName}-LibsqlLayerArn"
